### ISSUE TITLE
Owa extraction from omod

### ISSUE THREAD

**Issue by namratanehete** [SandeepRaparthi1/OWA-Commons#10]
Extract owa from omod modules and copy to owa.appfolderPath.

**Comment by namratanehete** [comment]
Is it done?

-----Original Message-----

**Comment by sandeepraparthi** [comment]
@namratanehete I felt this more regarding OWA-Module so closed this here and  created the issue in OWA-Module  same is with these two issues as well (https://github.com/SandeepRaparthi1/OWA-Commons/issues/9 and https://github.com/SandeepRaparthi1/OWA-Commons/issues/8)
